version: "3.9"

name: "fastifystarter"
services:
  postgres:
    image: postgres:alpine
    command:
      [
        "postgres",
        "-c",
        "log_statement=all",
        "-c",
        "log_destination=stderr",
        "-c",
        "wal_level=logical",
        "-c",
        "fsync=off",
      ]
    restart: always
    environment:
      POSTGRES_DB: fastifystarter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5
    volumes:
      - redis:/data

volumes:
  db:
  redis:
